name: DamagePenalty
version: '1.0.2'
main: github.tsffish.damagepenalty.DamagePenalty
api-version: '1.13'
commands:
  dpe:
    description: Hello Command
    usage: /dpe
  dpe reload:
    description: Reload Command
    usage: /dpe